name: Build and Push Web Image

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}:${{ github.ref_name }}"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:web"
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
