name: Build and Push Docker image

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:web"
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/srs-web:${{ github.ref_name }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
